### ISSUE TITLE
Running Cmder.exe leads to system error

### ISSUE THREAD

**Issue by felix1429** [bliker/cmder#497] opened 2015-05-20 03:17 UTC
I downloaded the full version of Cmder to a fresh install of Windows 8.1 but running Cmder.exe results in an error: "The program can't start because api-ms-win-crt-runtime-I1-1-0.dll is missing from your computer.  Try reinstalling the program to fix this problem".  I tried redownloading it and I ran windows update to see if that would fix it but it hasn't.

**Comment by Stanzilla** [comment] 2015-05-20 03:19
Duplicate of https://github.com/bliker/cmder/issues/482

**Comment by stoffeastrom** [comment] 2015-05-20 08:30
I get the same win7 x64. The #482 doesn't solve this issue.

**Comment by stoffeastrom** [comment] 2015-05-20 08:42
As @jstevans stated in #482 installing the  "Microsoft VC++ Redistributable 2015 RC." solved it for me

**Closed** 2015-05-20 09:18 UTC
Labels: duplicate
