### ISSUE TITLE
Script execution policy

### ISSUE THREAD

**Issue by Alexander-Karsten** [bliker/cmder#507] opened 2015-05-26 10:02 UTC
Hey,

I keep getting this error:

. : File C:\RailsInstaller\cmd\vendor\profile.ps1 cannot be loaded. The file
C:\RailsInstaller\cmd\vendor\profile.ps1 is not digitally signed. You cannot run this script on the current
system. For more information about running scripts and setting execution policy, see about_Execution_Policies
at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\RailsInstaller\cmd\vendor\conemu-maximus5\..\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

I have set my ExecutionPolicy to include remotesigned:
PS C:\Users\LX> Get-ExecutionPolicy -Scope CurrentUser
RemoteSigned

I can't seem to resolve this error, any help would be greatly appreciated!

**Comment by MartiUK** [comment] 2015-05-26 10:04
Duplicate of #483

**Closed** 2015-05-26 10:04 UTC
Labels: duplicate

**Comment by Alexander-Karsten** [comment] 2015-05-26 10:09
Sorry!

Thanks for the quick help.
