### ISSUE TITLE
fails to load on windows7- release v1.2

### ISSUE THREAD

**Issue by sarangbaheti** [bliker/cmder#488] opened 2015-05-18 18:25 UTC
Just downloaded and extracted [cmder.7z](https://github.com/bliker/cmder/releases/download/v1.2/cmder.7z), fails to load cmder with error:

---------------------------
Cmder.exe - System Error
---------------------------
The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

**Comment by MartiUK** [comment] 2015-05-18 18:55
Try the new archives I've uploaded. Thanks.

**Comment by Sabrethan** [comment] 2015-05-18 19:12
Also missing: `api-ms-win-crt-runtime-l1-1-0.dll`.

**Comment by jamesathey** [comment] 2015-05-18 19:50
I also get the same error:
"The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

**Comment by hellosputnik** [comment] 2015-05-18 21:28
I am running Windows 8.1 and I have the same errors as the ones in the comments above. This error was not present in the previous version of cmder.

**Comment by Stanzilla** [comment] 2015-05-18 21:45
https://www.microsoft.com/en-us/download/details.aspx?id=46881

if you are on a 64bit Windows, you need to install both versions.

**Comment by MartiUK** [comment] 2015-05-19 16:23
Duplicate of #482

**Closed by MartiUK** 2015-05-19 16:23 UTC
Labels: duplicate, Launcher

**Comment by b-long** [comment] 2015-05-27 12:11
:+1: I've yet to use `cmder` (working through this issue right now), but it would be great if the launcher could check for that dependency and then direct the user to https://www.microsoft.com/en-us/download/details.aspx?id=46881 if necessary.  Great job @bliker !

**Comment by Stanzilla** [comment] 2015-05-27 13:17
Yeah @MartiUK seems to be MIA, otherwise I can't explain why he keeps the project in such a broken state when the fix is so easy.

**Comment by MartiUK** [comment] 2015-05-27 13:19
@Stanzilla I'm not dead, just busy with work and my fiancée s quite ill at the moment and needs care. Don't worry I will try to get a portable version up and running soon.

**Comment by b-long** [comment] 2015-05-27 13:21
Understandable @MartiUK .  Hope things calm down (and your fiancée is in good health) soon.

**Comment by Stanzilla** [comment] 2015-05-27 13:32
All the best for you and your fiancee!
