### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll error

### ISSUE THREAD

**Issue by suconghou** [bliker/cmder#490] opened 2015-05-19 09:34 UTC
it needs api-ms-win-crt-runtime-l1-1-0.dll ,but i have not it.

**Comment by AlexandreGagner** [comment] 2015-05-19 09:40
:+1: 
Me too

**Comment by iam1980** [comment] 2015-05-19 09:42
same problem here. Have installed the latest Visual C++ Redistributable Packages for Visual Studio 2013 both 32 and 64biy

**Comment by AlexandreGagner** [comment] 2015-05-19 09:44
I just read in other issue that's need Visual C++ Redistr... 2015 so I'm trying with https://www.microsoft.com/en-US/download/details.aspx?id=46881

**Comment by suconghou** [comment] 2015-05-19 09:48
great , i have also fixed this problem , i just install vc++2015 both 64bit and 32bit ,it is ok now. see https://www.smartftp.com/support/kb/the-program-cant-start-because-api-ms-win-crt-runtime-l1-1-0dll-is-missing-f2702.html

**Comment by vBm** [comment] 2015-05-19 10:41
Ever since 53efab127ef0eff899910bc638cd2de074d86cfe you'd need 2015 redis.

:+1:

**Comment by MartiUK** [comment] 2015-05-19 12:03
I have made the decision to revert back to VC2013, since the re-distributable dlls are easily available to be packaged with the archives.

**Comment by Sabrethan** [comment] 2015-05-19 14:58
Do you have new download which uses the VC2013 files?

**Comment by Sabrethan** [comment] 2015-05-19 15:23
It would be nice to have Cmder has a portable app with all the necessary files provided.

**Comment by MartiUK** [comment] 2015-05-19 16:04
@Sabrethan Compiling it now

**Comment by MartiUK** [comment] 2015-05-19 16:23
Duplicate of #482 .

**Closed by MartiUK** 2015-05-19 16:23 UTC
Labels: duplicate, Launcher

**Comment by devravitiwari** [comment] 2015-05-27 08:39
It seems like the build is made from Visual Studio 2015. Hence need the Visual C++ runtime(vcrt). Please download from https://www.microsoft.com/en-US/download/details.aspx?id=46881

**Comment by guoqing10011001** [comment] 2015-05-30 14:08
great

**Comment by nesteruk** [comment] 2015-07-12 09:11
Same problem here. Please don't use non-RTM VS to build your software.

**Comment by aubrym** [comment] 2015-07-14 11:37
I have the same problem here.
I'm using Windows 8.1 and all VS C++ Redistributable packages installed.

Can you help me?

**Comment by devravitiwari** [comment] 2015-07-14 11:42
Download and install the CRT from https://www.microsoft.com/en-US/download/details.aspx?id=46881. It will resolve the issue.

**Comment by StudioLE** [comment] 2015-08-11 12:55
I'm getting 404 errors on all of the microsoft.com links people have posted here.

```
We are sorry, the page you requested cannot be found.
```

**Comment by devravitiwari** [comment] 2015-08-11 13:10
Better google "Visual C++ Redistributable for Visual Studio 2015". MS did changed the url that why 404. Here, you have the updated url, "https://www.microsoft.com/en-us/download/details.aspx?id=48145"

**Comment by avindra** [comment] 2015-08-11 13:35
Is it possible to just bundle the needed libs with the release? On my work laptop, there is a Win 7 installation that has limited access (i.e., I cannot install Visual C++ Redist 2015).

**Comment by Stanzilla** [comment] 2015-08-11 15:17
@avindra https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

**Comment by VenkatesanPrabhu** [comment] 2016-06-12 16:34
Great one from the author..thanks for the info about this error..
I've wrote a detailed article about it..
 http://www.wikitechy.com/fix-error/how-to-fix-the-api-ms-win-crt-runtime-l1-1.0.dll-is-missing  
Please visit! :)
