### ISSUE TITLE
cannot run cmder

### ISSUE THREAD

**Issue by ittayd** [bliker/cmder#516] opened 2015-06-04 05:54 UTC
I get the following dialog:
---------------------------
Cmder.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

**Comment by NicolasParada** [comment] 2015-06-04 06:42
Same here :(

**Comment by husa** [comment] 2015-06-04 09:49
duplicate of #501

**Closed** 2015-06-04 09:57 UTC
Labels: duplicate
