### ISSUE TITLE
Right-clicking Cmder's taskbar icon gets broken after a pinning and unpinning sequence

### ISSUE THREAD

**Issue by dcominottim** [bliker/cmder#254] opened 2014-09-04 05:33 UTC
100% reproducible on Windows 8.1 x64. Steps:

1. Launch Cmder from Windows Explorer
2. Right-click Cmder's taskbar icon and select "Pin this program to the taskbar"
3. Right-click Cmder's taskbar icon and select "Unpin this program from taskbar"
4. Try to right-click Cmder's taskbar icon again (no menu is shown)

**Comment by kevinclement** [comment] 2015-03-24 17:39
I'm seeing the same, icon changes to conemu default.  Would love to be able to pin this version.

**Comment by MartiUK** [comment] 2015-03-25 10:52
Duplicate of #251.

**Closed by MartiUK** 2015-03-25 10:52 UTC
Labels: duplicate
